version: "3.8"
services:

  db-auth:
    image: postgres
    container_name: db-auth
    environment:
      POSTGRES_PASSWORD: root
    expose: 
      - '5432'
    ports:
      - '5430:5432'
    networks:
      - backend 
    volumes:
      - ./db_init_scripts/auth:/docker-entrypoint-initdb.d/

  auth-service:
    image: auth-service
    build:
      context: ./Microservices/auth-service
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      - HOST_NAME=db
    expose: 
      - '8080'
    ports: 
      - '8080:8080'

networks:
  backend:
    name: nistagram
    driver: bridge